blog/web/router.ex
defmodule Blog.Router do
  use Blog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Blog.Auth, repo: Blog.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Blog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/session", SessionController, only: [:new, :create,:delete]
    resources "/videos", VideoController
  end

  scope "/manage", Blog do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Blog do
  #   pipe_through :api
  # end
end

blog/lib/blog/endpoint.ex
defmodule Blog.Endpoint do
  use Phoenix.Endpoint, otp_app: :blog

  socket "/socket", Blog.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :blog, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_blog_key",
    signing_salt: "jHrkTJJp"

  plug Blog.Router
end

blog/lib/blog/repo.ex
defmodule Blog.Repo do
  use Ecto.Repo, otp_app: :blog
end

blog/web/models/user.ex
defmodule Blog.User do
    use Blog.Web, :model

    schema "users" do
        field :name, :string
        field :username, :string
        field :password, :string, virtual: true
        field :password_hash, :string
        has_many :videos, Blog.Video
        timestamps()
    end

    def changeset(model, params \\ %{}) do
        # On definit la maniere de receuillir les donnees
        model
        |> cast(params, ~w(name username), []) # champs non vide dans le formulaire
        |> validate_length(:username, min: 4, max: 20) # longueur minimale
        |> validate_length(:name, min: 4, max: 50)
    end

    def registration_changeset(model, params) do
        model
        |> changeset(params)
        |> cast(params, ~w(password), [])
        |> validate_length(:password, min: 6, max: 100)
        |> put_pass_hash()
    end

    defp put_pass_hash(changeset) do
        case changeset do
            %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
                put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
                _ ->
                    changeset
        end
    end
end

blog/web/models/video.ex
defmodule Blog.Video do
  use Blog.Web, :model

  schema "videos" do
    field :url, :string
    field :title, :string
    field :description, :string
    field :tag, :string
    belongs_to :user, Blog.User, foreign_key: :user_id

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  @required_fields ~w(url title description tag)
  @optional_fields ~w()
  def changeset(struct, params \\ %{}) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_required([:url, :title, :description, :tag])
  end
end

blog/web/controllers/page_controller.ex
defmodule Blog.PageController do
  use Blog.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

blog/web/controllers/session_controller.ex
defmodule Blog.SessionController do
    use Blog.Web, :controller

    def new(conn, _) do
        render conn, "new.html"
    end

    def create(conn, %{"session" => %{"username" => user, "password" => pass}}) do
        case Blog.Auth.login_by_username_and_pass(conn, user, pass, repo: Repo) do
           {:ok, conn} ->
                conn
                |> put_flash(:info, "Welcome back !")
                |> redirect(to: page_path(conn, :index))
            {:error, _reason, conn} ->
                conn
                |> put_flash(:error, "invalide username/password combinaison")
                |> render("new.html")
        end
    end

    def delete(conn, _) do
        conn
        |> Blog.Auth.logout()
        |> redirect(to: page_path(conn, :index))
    end
end

blog/web/controllers/user_controller.ex
defmodule Blog.UserController do
    use Blog.Web, :controller

    # definir les alias
    alias Blog.User

    # Plug
    plug :authenticate_user when action in [:index, :show]

    def index(conn, _params) do
      users = Repo.all(Blog.User)
      render conn, "index.html", users: users
    end

    def new(conn, _params) do
        changeset = User.changeset(%User{})
        render conn, "new.html", changeset: changeset
    end

    def create(conn, %{"user" => user_params}) do
        changeset = User.registration_changeset(%User{}, user_params)
        case Repo.insert(changeset) do
            {:ok, user} ->
                conn
                |> Blog.Auth.login(user)
                |> put_flash(:info, "#{user.name} a ete creer avec succes!")
                |> redirect(to: user_path(conn, :index))
            {:error, changeset} ->
                render conn, "new.html", changeset: changeset
        end
    end

    def show(conn, %{"id" => id}) do
        user = Repo.get(Blog.User, id)
        render conn, "show.html", user: user
    end

   
end

blog/web/controllers/video_controller.ex
defmodule Blog.VideoController do
  use Blog.Web, :controller

  alias Blog.Video

  def index(conn, _params) do
    videos = Repo.all(Video)
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params) do
    changeset = Video.changeset(%Video{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}) do
    changeset = Video.changeset(%Video{}, video_params)

    case Repo.insert(changeset) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    video = Repo.get!(Video, id)
    render(conn, "show.html", video: video)
  end

  def edit(conn, %{"id" => id}) do
    video = Repo.get!(Video, id)
    changeset = Video.changeset(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}) do
    video = Repo.get!(Video, id)
    changeset = Video.changeset(video, video_params)

    case Repo.update(changeset) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    video = Repo.get!(Video, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(video)

    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: video_path(conn, :index))
  end
end

blog/web/views/error_view.ex
defmodule Blog.ErrorView do
  use Blog.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

blog/web/views/layout_view.ex
defmodule Blog.LayoutView do
  use Blog.Web, :view
end

blog/web/views/page_view.ex
defmodule Blog.PageView do
  use Blog.Web, :view
end

blog/web/views/session_view.ex
defmodule Blog.SessionView do
    use Blog.Web, :view
end

blog/web/views/user_view.ex
defmodule Blog.UserView do
    use Blog.Web, :view

    # alias 
    alias Blog.User

    def first_name(%User{name: name}) do
        name
        |> String.split(" ")
        |> Enum.at(0)
    end
end

blog/web/views/video_view.ex
defmodule Blog.VideoView do
  use Blog.Web, :view
end

blog/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Blog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    
      <header class="header">
        <ol class="breadcrumb text-right">
          <%= if @current_user do %>
            <li><%= @current_user.username %></li>
            <li><%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete"%>
          <% else %>
            <li><%= link "Log up", to: user_path(@conn, :new)%></li>   
            <li><%= link "Log in", to: session_path(@conn, :new)%></li>     
          <% end %>       
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

     <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

blog/web/templates/session/new.html.eex
<h1>Login</h1>
<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
    <div class="form-group">
        <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
    </div>
    <div class="form-group">
        <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
    </div>
    <%= submit "Log in", class: "btn btn-primary" %>
<% end %>

blog/web/templates/user/detailuser.html.eex
<b><%= first_name(@user) %></b><br>(<%= @user.id%>) <br>
<b><%= @user.username %></b>

blog/web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table class="table">
<%= for user <- @users do %>
<tr>
<td><%= render "user.html", user: user %></td>
<td><%= link "View", to: user_path(@conn, :show, user.id) %></td>
</tr>
<% end %>
</table>

blog/web/templates/user/new.html.eex
<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
    <%= if @changeset.action do %>
        <div class="alert alert-danger">
            <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
    <% end %>
    <div class="form-group">
        <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
        <%= error_tag f, :name %>
    </div>
    <div class="form-group">
        <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
        <%= error_tag f, :username %>
    </div>
    <div class="form-group">
        <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
        <%= error_tag f, :password %>
    </div>
<%= submit "Create User", class: "btn btn-primary" %>
<% end %>

blog/web/templates/user/show.html.eex
<%= render "detailuser.html", user: @user%>

blog/web/templates/user/user.html.eex
<b><%= first_name(@user) %></b>(<%= @user.id%>)

blog/web/templates/video/edit.html.eex
<h2>Edit video</h2>

<%= render "form.html", changeset: @changeset,
                        action: video_path(@conn, :update, @video) %>

<span><%= link "Back", to: video_path(@conn, :index) %></span>

blog/web/templates/video/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :url, class: "control-label" %>
    <%= text_input f, :url, class: "form-control" %>
    <%= error_tag f, :url %>
  </div>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :tag, class: "control-label" %>
    <%= text_input f, :tag, class: "form-control" %>
    <%= error_tag f, :tag %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

blog/web/templates/video/index.html.eex
<h2>Listing videos</h2>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Url</th>
      <th>Title</th>
      <th>Description</th>
      <th>Tag</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td><%= video.user_id %></td>
      <td><%= video.url %></td>
      <td><%= video.title %></td>
      <td><%= video.description %></td>
      <td><%= video.tag %></td>

      <td class="text-right">
        <span><%= link "Show", to: video_path(@conn, :show, video), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: video_path(@conn, :edit, video), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New video", to: video_path(@conn, :new) %></span>

blog/web/templates/video/new.html.eex
<h2>New video</h2>

<%= render "form.html", changeset: @changeset,
                        action: video_path(@conn, :create) %>

<span><%= link "Back", to: video_path(@conn, :index) %></span>

blog/web/templates/video/show.html.eex
<h2>Show video</h2>

<ul>

  <li>
    <strong>User:</strong>
    <%= @video.user_id %>
  </li>

  <li>
    <strong>Url:</strong>
    <%= @video.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @video.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @video.description %>
  </li>

  <li>
    <strong>Tag:</strong>
    <%= @video.tag %>
  </li>

</ul>

<span><%= link "Edit", to: video_path(@conn, :edit, @video) %></span>
<span><%= link "Back", to: video_path(@conn, :index) %></span>